### ISSUE TITLE
Dev-C++ 6.3.0 Path

### ISSUE THREAD

**Issue by ObscenityIB** [AM71113363/SkinPackCreatorV2#1]
Latest Dev-C++ 6.3.0 path for `make` command is `.\TDM-GCC-64\bin\mingw32-make.exe`

**Comment by AM71113363** [comment]
build.bat & makefile in this DIR are only for beginners who don't "TRUST" running ".EXE" on their PC, and want to rebuild it.
#They can download DevCpp(v4.9.9.*) from http://www.bloodshed.net/
#Others(NOT beginners) already know how to create a new-project and rebuild it.
